AWSTemplateFormatVersion: 2010-09-09
Description: Trivia Trials Dynamo, API Gateway and Lambda function for getting leaderboard

Resources:
  LambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "GetLeaderboardLambdaRole"
        ManagedPolicyArns: 
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        AssumeRolePolicyDocument: 
          Version: 2012-10-17
          Statement:
            - 
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - 
            PolicyName: "dynamodbWriteAccess"
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 
                    - !Sub arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/GameScores

  GetLeaderboardFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        S3Bucket: trivia-trials-config-bucket
        S3Key: get_leaderboard/get_leaderboard.zip
      FunctionName: GetLeaderboard
      Handler: get_leaderboard.handler

      Role: !GetAtt LambdaRole.Arn
      MemorySize: 128
      Runtime: python3.9


  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API Gateway for getting leaderboard from GameScores
      EndpointConfiguration:
        Types:
          - EDGE
      Name: TriviaTrialsGetLeaderboardGateway

  apiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${GetLeaderboardFunction.Arn}/invocations
      ResourceId: !GetAtt apiGateway.RootResourceId
      RestApiId: !Ref apiGateway

  apiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - apiGatewayRootMethod
    Properties:
      RestApiId: !Ref apiGateway
      StageName: TriviaTrialsGetLeaderboardGateway

  lambdaApiGatewayInvoke:
    DependsOn:
      - GetLeaderboardFunction
      - apiGatewayDeployment
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: GetLeaderboard
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:us-east-1:${AWS::AccountId}:wp7xky1zbb/*

  lambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/GetLeaderboard
      RetentionInDays: 60

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub https://${apiGateway}.execute-api.us-east-1.amazonaws.com/TriviaTrialsGetLeaderboardGateway

  lambdaArn:
    Value: !GetAtt GetLeaderboardFunction.Arn