AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: trivia-trials-config-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false 
        IgnorePublicAcls: false
