AWSTemplateFormatVersion: 2010-09-09
Description: Trivia Trials Dynamo, API Gateway and Lambda function for saving score

# Parameters:
#   apiGatewayName:
#     Type: String
#     Default: my-api
#   apiGatewayStageName:
#     Type: String
#     AllowedPattern: "[a-z0-9]+"
#     Default: call
#   apiGatewayHTTPMethod:
#     Type: String
#     Default: POST
#   lambdaFunctionName:
#     Type: String
#     AllowedPattern: "[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+"
#     Default: my-function

Resources:
  DynamoDB:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "GameScoreId"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "GameScoreId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      TableName: GameScores

  LambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "SaveScoreLambdaRole"
        ManagedPolicyArns: 
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        AssumeRolePolicyDocument: 
          Version: 2012-10-17
          Statement:
            - 
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - 
            PolicyName: "dynamodbWriteAccess"
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:PutItem
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 
                    - !GetAtt DynamoDB.Arn

  SaveScoreFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        ImageUri: public.ecr.aws/lambda/python:3.9
        S3Bucket: trivia-trials-config-bucket
        S3Key: save_score/save_score.zip
      FunctionName: SaveScore
      Handler: save_score.handler
      Role: !GetAtt LambdaRole.Arn
      MemorySize: 128
      Runtime: python3.9


  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API Gateway for saving scores
      EndpointConfiguration:
        Types:
          - EDGE
      Name: TriviaTrialsSaveScoreApiGateway

  apiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${SaveScoreFunction.Arn}/invocations
      ResourceId: !GetAtt apiGateway.RootResourceId
      RestApiId: !Ref apiGateway


  TestApiMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        AuthorizationType: NONE
        HttpMethod: POST
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${SaveScoreFunction.Arn}/invocations
        ResourceId: !GetAtt apiGateway.RootResourceId
        RestApiId: !Ref apiGateway

  apiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - apiGatewayRootMethod
    Properties:
      RestApiId: !Ref apiGateway
      StageName: TriviaTrialsSaveScoreApiGateway

  lambdaApiGatewayInvoke:
    DependsOn:
      - SaveScoreFunction
      - apiGatewayDeployment
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: SaveScore
      Principal: apigateway.amazonaws.com
      SourceArn: arn:aws:execute-api:us-east-1:049850382269:6eje8pht04/*

  lambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/SaveScore
      RetentionInDays: 60

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub https://${apiGateway}.execute-api.us-east-1.amazonaws.com/TriviaTrialsSaveScoreApiGateway

  lambdaArn:
    Value: !GetAtt SaveScoreFunction.Arn