name: Build and Deploy SaveScore Python Lambda to S3 2

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    paths: 
      - lambdas/save_score/**
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-deploy-start-game-lambda-to-s3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

    - name: Install dependencies with LambCI
      run: |
        cd lambdas/save_score/
        pip install -r requirements.txt -t .

    - name: Run Unit Tests
      run: |
        cd lambdas/save_score/

    - name: Bundle function with dependencies
      run: |
        cd lambdas/save_score/
        zip -r build.zip .

    - name: Copy function zip file to S3
      run: |
          aws s3 cp lambdas/save_score/build.zip s3://trivia-trials-config-bucket/save_score/save_score.zip

    - name: Update function from S3
      run: |
          aws lambda update-function-code --function-name SaveScore --s3-bucket trivia-trials-config-bucket --s3-key save_score/save_score.zip
